### ISSUE TITLE
Build.PL failure

### ISSUE THREAD

**Issue by Manwar** [stevan/plack-middleware-session#26]
Hi,

As a part of CPAN Pull Request Challenge, I have been looking at the distribution "Plack-Middleware-Session" closely. In my research, I noticed if I try to install the distribution using Build.PL script, I get dependency error thrown as below:

      manwar@ubuntu:~/my-github/plack-middleware-session$ perl Build.PL
      Creating new 'Build' script for 'Plack-Middleware-Session' version '0.25'

      manwar@ubuntu:~/my-github/plack-middleware-session$ ./Build 
      cp lib/Plack/Session.pm blib/lib/Plack/Session.pm
      cp lib/Plack/Session/State.pm blib/lib/Plack/Session/State.pm
      cp lib/Plack/Session/Store.pm blib/lib/Plack/Session/Store.pm
      cp lib/Plack/Session/Store/File.pm blib/lib/Plack/Session/Store/File.pm
      cp lib/Plack/Middleware/Session.pm blib/lib/Plack/Middleware/Session.pm
      cp lib/Plack/Session/Store/DBI.pm blib/lib/Plack/Session/Store/DBI.pm
      cp lib/Plack/Session/Store/Null.pm blib/lib/Plack/Session/Store/Null.pm
      cp lib/Plack/Middleware/Session/Cookie.pm blib/lib/Plack/Middleware/Session/Cookie.pm
      cp lib/Plack/Session/State/Cookie.pm blib/lib/Plack/Session/State/Cookie.pm
      cp lib/Plack/Session/Store/Cache.pm blib/lib/Plack/Session/Store/Cache.pm

      manwar@ubuntu:~/my-github/plack-middleware-session$ ./Build test
      t/000_load.t ................... 1/? 
      #   Failed test 'use Plack::Middleware::Session;'
      #   at t/000_load.t line 8.
      #     Tried to use 'Plack::Middleware::Session'.
      #     Error:  Can't locate Plack/Util.pm in @INC (@INC contains: /home/manwar/my-github/plack-    
      middleware-session/blib/arch /home/manwar/my-github/plack-middleware-session/blib/lib  
      /etc/perl /usr/local/lib/perl/5.10.1 /usr/local/share/perl/5.10.1 /usr/lib/perl5 /usr/share/perl5      
      /usr/lib/perl/5.10 /usr/share/perl/5.10 /usr/local/lib/site_perl .) at /home/manwar/my-github/plack-  
      middleware-session/blib/lib/Plack/Middleware/Session.pm line 8.
      # BEGIN failed--compilation aborted at /home/manwar/my-github/plack-middleware-   
      session/blib/lib/Plack/Middleware/Session.pm line 8.
      # Compilation failed in require at t/000_load.t line 8.
      # BEGIN failed--compilation aborted at t/000_load.t line 8.
      Use of uninitialized value $reason in concatenation (.) or string at  
      /usr/local/share/perl/5.10.1/Test/Builder.pm line 1272.
      Bailout called.  Further testing stopped:  
      # Tests were run but no plan was declared and done_testing() was not seen.
      # Looks like your test exited with 255 just after 1.
      FAILED--Further testing stopped.

It could be the Build.PL, part of the distribtion and generated by Dist::Zilla::Plugin::ModuleBuildTiny 0.007, seems to be broken.

I must admit here that I am not familiar with the new way of build/install CPAN modules. I still use the traditional Makefile.PL/Build.PL file to install the distribution.

If I use the command "sudo cpanm ." to install the distribution, it works like a charm.

Am I not using the Build.PL script correctly?

If you agree then I can create a traditional Build.PL by hand, with details of all pre-requisites and all other meta information.

Best Regards,
Mohammad S Anwar

**Comment by miyagawa** [comment]
> Am I not using the Build.PL script correctly?

Right, manual invocation is not the right way to install it. As you figured out that `cpanm .` works just fine, CPAN installers including CPAN.pm, cpanm, CPANPLUS are all able to install the dependencies by scanning META.json.

> If you agree then I can create a traditional Build.PL by hand, with details of all pre-requisites and all other meta information.

No, please do not do that.
