### ISSUE TITLE
SEE ALSO link broken in Plack::Middleware::Session::Cookie

### ISSUE THREAD

**Issue by Manwar** [stevan/plack-middleware-session#27]
Hi,

In the "SEE ALSO" section of the package Plack::Middleware::Session::Cookie, the link for "Rack::Session::Cookie" is broken.
Is it a typo? 

I couldn't find any distribution by that name in CPAN search.

Best Regards,
Mohammad S Anwar

**Comment by miyagawa** [comment]
it is a Ruby gem. http://www.rubydoc.info/github/rack/rack/Rack/Session/Cookie
